### ISSUE TITLE
Can't get this action to render preview correctly

### ISSUE THREAD

**Issue by gcapes** [vliz-be-opsci/rocrate-to-pages#13]
Hi, 
I've been trying to use this action but haven't had a successful build. I am new to GitHub actions so hopefully I've just missed something.

I've [set up the workflow](https://github.com/gcapes/test-rocrate-to-pages/tree/master/.github/workflows) and while the action runs, it doesn't correctly build [the preview](https://gcapes.github.io/test-rocrate-to-pages/).

The metadata.json file does build correctly [using ro-crate-html-js](https://github.com/gcapes/rocrate-to-pages/blob/test/.github/workflows/rocrate_to_pages.yml) and [looks like this](https://gcapes.github.io/rocrate-to-pages/)

Thanks!

@stain

**Comment by cedricdcc** [comment]
Hey sorry for the late reply , We are currently in the works of revamping the complete action because of a mayor oversight in out part.

I will reach out to you when we have a working version again @gcapes
