### ISSUE TITLE
Add fancy CSV viewer

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/rocrate-to-pages#16]
- [x] :  Filter rows by input variable «search»
- [ ] #17
- [x] : x-y axis scrollbar within csv container
- [x] : custom themed formatting , condensed/striped etc
- [x] : (optional) all params above in fragment id for in app routing  -> check for some standard for encoding this kind of stuff maybe align with `:~:text=` [text-fragment syntax](https://developer.mozilla.org/en-US/docs/Web/Text_fragments)
- [x] : also highlight the matching words that are filtered --> again maybe the `:~:text=` system has a way to highlight ALL matches, not only the first ?
- [x] : when filtering by «search» provide feedback to the end user about the fact that not all rows are shown --> some wording like `only showing x matching rows out of N total`  vs `showing all N rows` if no filtering is on
- [ ] #18

**Comment by marc-portier** [comment]
adding some features to the request
