### ISSUE TITLE
Styling: Bump release to include header/footer templating

### ISSUE THREAD

**Issue by RoryMMMM** [vliz-be-opsci/rocrate-to-pages#4]
Include header/footer styling in new release

**Comment by marc-portier** [comment]
discussed 2022-05-10

investigate into this strategy:
- allow the rocrat-to-pages.yml to inject the selected theme
- could be by name / ref t o the theme-repo to use
- but could as well be the jekyll project one can (partially) clone to grab the style it declare
- in fact could be the ocean-sampling-day/rocrate-to-pages-style
- being a chosen fixed name,, we could maybe even default to that?

**Comment by RoryMMMM** [comment]
Solved: 

- New template repo created ocean-sampling-day/pages-theme
- Jekyll theme  forked into repo
- index.html created to combine README.md and rocrate-preivew.html
- new workflow.yaml written to combine actions
- actions deployed and tested on 2019 and ro-test-crate
