### ISSUE TITLE
not all video formats seem to play

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/rocrate-to-pages#9]
https://vliz-be-opsci.github.io/test-rocrate-media/#./video/

might be due to codecs or platform or what not - might be useful to test, understand and document (possibly inline)

**Comment by cedricdcc** [comment]
The formats of the videos in the test-ro-crate media are indeed there to test out the diff formats. Perhaps better to make a separate issue per format that isn't playing so we can tackle them one by one.
